### ISSUE TITLE
Learn Mode: Fruit outline disappears when zoomed in

### ISSUE THREAD

**Issue by eaisley** [Retronator/Pixel-Art-Academy#116]
In Pixel Art Academy: Learn Mode, build 0.21.3 on Windows. 

Under the tutorial section for lines, in the lesson "Outline" where you draw three fruits, when selecting the third fruit reference: The new page area appeared, and the outline for the fruit appeared, however when zooming in, the outline disappears. 

I've tested this with the different orders of all the fruits, and it's only the final fruit reference, regardless of which order they're selected in. Sometimes the second fruit outline will disappear inconsistently, and the first fruit always seems to be fine.

![image](https://github.com/user-attachments/assets/1ffaf077-b158-4c6f-b907-148f2dbcf726)

**Comment by MatejJan** [comment]
Thank you for reporting this, will investigate!
