### ISSUE TITLE
Error uploading a doodle to the journal

### ISSUE THREAD

**Issue by devstrat** [Retronator/Pixel-Art-Academy#70]
Version: alpha build 0.41.4
I was attempting to finish the task of creating a doodle but was not able to upload the result to the journal at all. 
Error messages:

> 2d833a1670f6d28f6a125782dc3b23ec5941c55e3.js?meteor_js_resource=true:271 OPTIONS https://pixelartacademy.s3.amazonaws.com/ 403 (Forbidden)

> /pixelboy/journal/NuAgMPyYzjyDZ3EJb:1 Access to XMLHttpRequest at 'https://pixelartacademy.s3.amazonaws.com/' from origin 'https://landsofillusions.world' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

> d833a1670f6d28f6a125782dc3b23ec5941c55e3.js?meteor_js_resource=true:277 Error uploading file. r {isClientSafe: true, error: " - 0", reason: "Failed to upload file to cloud storage", details: undefined, message: "Failed to upload file to cloud storage [ - 0]", …}

<img width="1440" alt="Screenshot 2019-03-16 at 23 30 07" src="https://user-images.githubusercontent.com/10435863/54482442-c2387780-4843-11e9-9eef-be88f22789ed.png">

Cheers!

**Comment by MatejJan** [comment]
Thank you, fixed!
