### ISSUE TITLE
Stuck in loader

### ISSUE THREAD

**Issue by metakermit** [Retronator/Pixel-Art-Academy#94]
Hi, I keep trying to get from the textual part of the game to the graphical parts I see in your updates, but I keep getting stuck. Right now I can't leave the https://pixelart.academy/loader part which I see right after I enter Lands of Illusions. I tried reloading, but it takes me to the same saved spot where there is apparently nothing I can do. Any tips?

<img width="885" alt="Screenshot 2021-01-21 at 13 05 54" src="https://user-images.githubusercontent.com/1818628/105349804-86625c00-5bea-11eb-857e-b0d76ad4b9bf.png">

This appears to be different to the behaviour I see in the [walkthrough video](https://youtu.be/XO8sijzy8Fg).

The version I see is Alpha build 0.58.4.

**Comment by MatejJan** [comment]
Hi, if you're comfortable using the browser console, can you check what timeline you're on by running:
```
LOI.adventure.currentTimelineId()
```
If it's not `Construct`, change it to that with:
```
LOI.adventure.setTimelineId(LOI.TimelineIds.Construct)
```
Then you should be in the Loader and in your inventory you should have SYNC. Then you can type EXIT in the text interface to get back out to the real world.

**Comment by metakermit** [comment]
Hey, I am comfortable using the browser console. Tried the suggestions, but this didn't help. What I enter as a command just gets repeated again and I see this error:

```
Uncaught TypeError: Cannot read property 'likelihood' of undefined
    at e.chooseLikelyAction (5e2a8bdad9aeb868d6321b3ed9d408f5cfbb7b13.js?meteor_js_resource=true:290)
    at e.parse (5e2a8bdad9aeb868d6321b3ed9d408f5cfbb7b13.js?meteor_js_resource=true:290)
    at e._executeCommand (5e2a8bdad9aeb868d6321b3ed9d408f5cfbb7b13.js?meteor_js_resource=true:290)
    at e.onCommandInputEnter (5e2a8bdad9aeb868d6321b3ed9d408f5cfbb7b13.js?meteor_js_resource=true:290)
    at Object.onEnter (5e2a8bdad9aeb868d6321b3ed9d408f5cfbb7b13.js?meteor_js_resource=true:290)
    at e.onKeyDown (5e2a8bdad9aeb868d6321b3ed9d408f5cfbb7b13.js?meteor_js_resource=true:290)
    at HTMLDocument.<anonymous> (5e2a8bdad9aeb868d6321b3ed9d408f5cfbb7b13.js?meteor_js_resource=true:290)
    at HTMLDocument.dispatch (5e2a8bdad9aeb868d6321b3ed9d408f5cfbb7b13.js?meteor_js_resource=true:102)
    at HTMLDocument.v.handle (5e2a8bdad9aeb868d6321b3ed9d408f5cfbb7b13.js?meteor_js_resource=true:102)
```

![Screenshot 2021-01-26 at 12 21 26](https://user-images.githubusercontent.com/1818628/105839105-47a91900-5fd1-11eb-9069-0f06f5335684.png)

**Comment by MatejJan** [comment]
Hm, a few more diagnostics you can try is to run these lines, one by one:
```
LOI.characterId() // shoud be null
LOI.adventure.activeItemId() // should be null
LOI.adventure.currentLocationId() // should be LandsOfIllusions.Construct.Loading
LOI.adventure.gameStateSource() // should be DatabaseUser
```
In any case, you can try by manually kicking yourself out of the construct by running, one by one:
```
LOI.adventure.setTimelineId('RealLife')
LOI.adventure.goToLocation('Retronator.HQ.Cafe')
```
Does this place you in the Cafe and restore your inventory?

**Comment by metakermit** [comment]
Yes, the remaining diagnostics are also as you expect:

```
$ LOI.characterId() // shoud be null
null

$ LOI.adventure.activeItemId() // should be null
null

$ LOI.adventure.currentLocationId() // should be LandsOfIllusions.Construct.Loading
"LandsOfIllusions.Construct.Loading"

$ LOI.adventure.gameStateSource() // should be DatabaseUser
"DatabaseUser"
```

Doing `LOI.adventure.setTimelineId('RealLife')` triggered the next part from the walkthrough video (the conversation with the captain). After this I entered "use sync", but my keyboard then froze, i.e. I couldn't enter any other commands.

![Screenshot 2021-01-26 at 14 41 32](https://user-images.githubusercontent.com/1818628/105852318-9b712d80-5fe4-11eb-8e32-cc7f64251b2a.png)

I'm seeing this error in the console now:

```
Exception from Tracker recompute function:
AssertionError: Component 'LandsOfIllusions.Items.Sync' parent component 'Render' already set.
```

**Comment by metakermit** [comment]
After quitting and loading I can use sync now. I can't 'look at tv' when I'm in the loader like in the walkthrough (says can't do that).

![Screenshot 2021-01-26 at 14 52 49](https://user-images.githubusercontent.com/1818628/105853715-43d3c180-5fe6-11eb-9f18-8983f5bef7cb.png)

Not sure how I'm supposed to make my character now and continue.

**Comment by MatejJan** [comment]
Yeah, sometimes (many times actually), refreshing the page helps to fix any hanging errors (unfortunately the game doesn't crash like desktop games do, so all you get is a silent crash in the console).

The TV from the old video has been removed. Instead you go out of the Loading program (type EXIT or using SYNC UI choose disconnect) and to Cyborg Construction Center. Burra at the Cafe can circle it for you on the map. There you will create a character (or choose from a premade one, like on the TV in the video).

Thanks for your patience with this as things are still broken. The whole Loading section will be eventually removed when I get time to rewrite the intro.
